version: '3.9'
services:
  develop:
    image: 'node:16.8-alpine3.11'
    container_name: digital-menu-app
    # restart: always
    working_dir: /digital-menu
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/digital-menu
      - nodemodules:/digital-menu/node_modules
    command: "npm run serve"
volumes:
  nodemodules: {}
